version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/gatsby-site
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Gatsby Build
          command: yarn build
      - run:
          name: deploy
          command: yarn deploy-ftp